In [8]:
import numpy as np
import tensorflow as tf

In [ ]:
#----------------------- init

In [12]:
np.array([[]])

array([], shape=(1, 0), dtype=float64)

In [9]:
tf.convert_to_tensor([2.0,3.0])

<tf.Tensor: id=0, shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [ ]:
#------------------------------ attribute

In [ ]:
arr.shape
arr.dtype



In [ ]:
#------------------------------ one hot

In [5]:
#设置类别的数量
num_classes = 10
#需要转换的整数
arr = np.array([1,3,4,5,9])
print(arr.shape)

#将整数转为一个10位的one hot编码
print()

(5,)
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
#----------------------- 拼接扩展

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(a.shape, b.shape)
print(np.concatenate((a, b), axis=0).shape)

[[1 2]
 [3 4]]
(2, 2) (1, 2)
(3, 2)


In [20]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
input_array = np.random.randint(1000, size=(32, 10))
input_array = np.concatenate(
    (input_array, np.random.randint(1000, size=(1, 10))), 
    axis=0
)